export const CONTROL_TEXTS = {
  drawing: {
    saveButton: "Save Drawing",
    exportButton: "Export to .hxf",
    importHxfButton: "Import .hxf",
    exportModalTitle: "Export as .hxf",
    exportModalPlaceholder: "File name",
    exportModalConfirm: "Export",
    exportModalCancel: "Cancel",
    exportModalClose: "Close export dialog",
    hxfImportErrorTitle: "Import failed",
    hxfImportParseError: "This file is not valid .hxf (JSON) data.",
    hxfImportGridError: "Pattern must be a full grid of 0s and 1s matching the drawing canvas size.",
    hxfImportSavingStatus: "Saving pattern…",
    hxfImportCompleteMessage: "Import complete",
    hxfImportCloseLabel: "Close",
    clearCanvasButton: "Clear canvas",
    restoreButton: "Restore",
    restoreDisabledHint: "Restore drawing after changes",
    savedPatternsLabel: "Saved patterns",
    cursorCoordinatesLabel: "Cursor coordinates",
    cursorXAxisLabel: "X",
    cursorYAxisLabel: "Y",
    brushSizeLabel: "Brush Size",
    brushShapeLabel: "Brush Shape",
    tools: {
      pencilAlt: "pencil",
      eraserAlt: "eraser",
      handAlt: "hand",
    },
    shapes: {
      square: "Square",
      cross: "Cross",
      hollowSquare: "Hollow Square",
      circle: "Circle",
      hollowCircle: "Hollow Circle",
      diamond: "Diamond",
      hollowDiamond: "Hollow Diamond",
      hline: "H-Line",
      vline: "V-Line",
      x: "X-Shape",
    },
  },
  userCustomSelector: {
    placeholder: "select custom pattern",
    prompt: {
      title: "save custom preset",
      inputPlaceholder: "preset name",
      confirmButtonText: "save",
      cancelButtonText: "cancel",
      closeButtonLabel: "close modal",
      filenameRequired: "filename required",
    },
  },
} as const;
